[build]
buildpacks = ["heroku/nodejs"]

[env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[processes]
web = "node server.js"

[scripts]
build = "bun scripts/build.ts"
test = "bun scripts/test.ts"

[metadata]
name = "hukusis-agents"
version = "1.0.0"
description = "Hukusis Agents - Türkiye hukuk sistemi ve çeşitli uzmanlık alanları için özel olarak tasarlanmış AI asistanlar koleksiyonu"

[engines]
node = ">=18.0.0"
bun = ">=1.0.0"

[dependencies]
"@lobehub/lint" = "^1.24.3"
"@octokit/rest" = "^20.1.1"
"consola" = "^3.2.3"
"dayjs" = "^1.11.12"
"dirty-json" = "^0.9.2"
"dotenv" = "^16.4.5"
"fs-extra" = "^11.2.0"
"langchain" = "0.1.37"
"lodash-es" = "^4.17.21"
"p-map" = "^7.0.2"
"zod" = "^3.23.8"
"zod-to-json-schema" = "^3.23.2"

[dev-dependencies]
"@types/fs-extra" = "^11.0.4"
"@types/lodash-es" = "^4.17.12"
"@types/node" = "^20.14.14"
"eslint" = "^8.57.0"
"prettier" = "^3.3.3"
"remark" = "^14.0.3"
"remark-cli" = "^11.0.0"
"remark-pangu" = "^2.2.0"
"semantic-release" = "^21.1.2"
"typescript" = "^5.5.4" 